-- GENERATED by `make generate` from configs/sources/steel_meters.yml — do not edit by hand.
-- Source unit: kWh (× 1.0 → kWh)
select
    md5(concat_ws('|', 'steel_meters', facility_id, cast(reading_ts as varchar))) as reading_id,
    facility_id,
    'steel' as industry,
    'steel_meters' as source_name,
    reading_ts,
    energy_value * 1.0 as energy_kwh,
    pipeline_run_id,
    loaded_at
from {{ source('raw', 'src_steel_meters') }}
