-- GENERATED by `make generate` from configs/sources/chem_scada.yml — do not edit by hand.
-- Source unit: MJ (× 0.2777778 → kWh)
select
    md5(concat_ws('|', 'chem_scada', facility_id, cast(reading_ts as varchar))) as reading_id,
    facility_id,
    'chemicals' as industry,
    'chem_scada' as source_name,
    reading_ts,
    energy_value * 0.2777778 as energy_kwh,
    pipeline_run_id,
    loaded_at
from {{ source('raw', 'src_chem_scada') }}
