-- GENERATED by `make generate` from configs/sources/textile_looms.yml — do not edit by hand.
-- Source unit: MWh (× 1000.0 → kWh)
select
    md5(concat_ws('|', 'textile_looms', facility_id, cast(reading_ts as varchar))) as reading_id,
    facility_id,
    'textile' as industry,
    'textile_looms' as source_name,
    reading_ts,
    energy_value * 1000.0 as energy_kwh,
    pipeline_run_id,
    loaded_at
from {{ source('raw', 'src_textile_looms') }}
