-- GENERATED by `make generate` from all source templates in configs/sources/ — do not edit by hand.
-- The versioned public model. Its shape is governed by
-- configs/contracts/energy_readings_v1.yml (additive-only evolution).
select * from {{ ref('stg_chem_scada') }}
union all
select * from {{ ref('stg_steel_meters') }}
union all
select * from {{ ref('stg_textile_looms') }}
