-- GENERATED by `make generate` from configs/metrics.yml — do not edit by hand.
-- Every metric below is defined once, in the registry, and rendered here.
select
    facility_id,
    industry,
    cast(date_trunc('day', reading_ts) as date) as reading_date,
    -- Total energy consumed per facility per day, in kWh.
    sum(energy_kwh) as daily_energy_kwh,
    -- Number of readings received that day (gap detection).
    count(*) as reading_count,
    -- Largest single reading of the day.
    max(energy_kwh) as peak_reading_kwh,
    -- Mean reading size; with hourly sources this approximates average load in kW.
    avg(energy_kwh) as avg_reading_kwh
from {{ ref('energy_readings_v1') }}
group by 1, 2, 3
