"""Render dbt models from the templates: configuration in, SQL out.

`make generate` turns each source template into a staging model (with tests),
unions them into the versioned public mart, and renders the metric registry
into the daily rollup. The generated files carry a DO NOT EDIT header; the
templates in configs/ are the only place a human edits.
"""
from __future__ import annotations

import os

from .config import UNIT_TO_KWH, load_metrics, load_source_configs

HEADER = "-- GENERATED by `make generate` from {src} — do not edit by hand.\n"
YML_HEADER = "# GENERATED by `make generate` — do not edit by hand.\n"

STAGING_DIR = "warehouse/models/staging"
MARTS_DIR = "warehouse/models/marts"


def _staging_sql(cfg: dict) -> str:
    name = cfg["source_name"]
    factor = UNIT_TO_KWH[cfg["energy_unit"]]
    return (
        HEADER.format(src=f"configs/sources/{name}.yml")
        + f"-- Source unit: {cfg['energy_unit']} (× {factor} → kWh)\n"
        + "select\n"
        + f"    md5(concat_ws('|', '{name}', facility_id, cast(reading_ts as varchar))) as reading_id,\n"
        + "    facility_id,\n"
        + f"    '{cfg['industry']}' as industry,\n"
        + f"    '{name}' as source_name,\n"
        + "    reading_ts,\n"
        + f"    energy_value * {factor} as energy_kwh,\n"
        + "    pipeline_run_id,\n"
        + "    loaded_at\n"
        + f"from {{{{ source('raw', 'src_{name}') }}}}\n"
    )


def _staging_schema_yml(configs: list[dict]) -> str:
    lines = [YML_HEADER, "version: 2", "", "models:"]
    for cfg in configs:
        name = cfg["source_name"]
        lines += [
            f"  - name: stg_{name}",
            f"    description: '{cfg.get('description', name)} (standardized to the canonical schema)'",
            "    columns:",
            "      - name: reading_id",
            "        tests: [unique, not_null]",
            "      - name: facility_id",
            "        tests: [not_null]",
            "      - name: reading_ts",
            "        tests: [not_null]",
            "      - name: energy_kwh",
            "        tests: [not_null]",
        ]
    return "\n".join(lines) + "\n"


def _sources_yml(configs: list[dict]) -> str:
    lines = [YML_HEADER, "version: 2", "", "sources:", "  - name: raw", "    schema: raw", "    tables:"]
    for cfg in configs:
        lines.append(f"      - name: src_{cfg['source_name']}")
    lines.append("      - name: run_audit")
    lines.append("      - name: quarantine")
    return "\n".join(lines) + "\n"


def _mart_union_sql(configs: list[dict]) -> str:
    selects = [f"select * from {{{{ ref('stg_{c['source_name']}') }}}}" for c in configs]
    return (
        HEADER.format(src="all source templates in configs/sources/")
        + "-- The versioned public model. Its shape is governed by\n"
        + "-- configs/contracts/energy_readings_v1.yml (additive-only evolution).\n"
        + "\nunion all\n".join(selects)
        + "\n"
    )


def _mart_daily_sql(metrics: dict) -> str:
    grain = metrics["grain"]
    dims = ",\n".join(f"    {g}" for g in grain if g != "reading_date")
    metric_lines = ",\n".join(
        f"    -- {m.get('description', m['name'])}\n    {m['expression']} as {m['name']}"
        for m in metrics["metrics"]
    )
    return (
        HEADER.format(src="configs/metrics.yml")
        + "-- Every metric below is defined once, in the registry, and rendered here.\n"
        + "select\n"
        + f"{dims},\n"
        + "    cast(date_trunc('day', reading_ts) as date) as reading_date,\n"
        + f"{metric_lines}\n"
        + "from {{ ref('energy_readings_v1') }}\n"
        + f"group by {', '.join(str(i + 1) for i in range(len(grain)))}\n"
    )


def _marts_schema_yml(metrics: dict) -> str:
    lines = [
        YML_HEADER, "version: 2", "", "models:",
        "  - name: energy_readings_v1",
        "    description: 'Versioned public model — one row per reading, all industries, kWh.'",
        "    columns:",
        "      - name: reading_id",
        "        tests: [unique, not_null]",
        "      - name: energy_kwh",
        "        tests: [not_null]",
        f"  - name: {metrics['model']}",
        "    description: 'Daily rollup rendered from the metric registry (configs/metrics.yml).'",
        "    columns:",
        "      - name: facility_id",
        "        tests: [not_null]",
        "      - name: reading_date",
        "        tests: [not_null]",
    ]
    return "\n".join(lines) + "\n"


def generate_all() -> list[str]:
    configs = load_source_configs()
    metrics = load_metrics()
    os.makedirs(STAGING_DIR, exist_ok=True)
    os.makedirs(MARTS_DIR, exist_ok=True)
    written = []

    def write(path: str, content: str):
                with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        written.append(path)

    for cfg in configs:
        write(os.path.join(STAGING_DIR, f"stg_{cfg['source_name']}.sql"), _staging_sql(cfg))
    write(os.path.join(STAGING_DIR, "schema.yml"), _staging_schema_yml(configs))
    write(os.path.join(STAGING_DIR, "sources.yml"), _sources_yml(configs))
    write(os.path.join(MARTS_DIR, "energy_readings_v1.sql"), _mart_union_sql(configs))
    write(os.path.join(MARTS_DIR, f"{metrics['model']}.sql"), _mart_daily_sql(metrics))
    write(os.path.join(MARTS_DIR, "schema.yml"), _marts_schema_yml(metrics))
    return written
